#ifndef _LIBWFS_INFRA_NAMESPACE_H
#define _LIBWFS_INFRA_NAMESPACE_H

#include <stdint.h>

enum InfraNamespace : uint8_t {
  INFRA_NAMESPACE_NONE = 0,

  INFRA_NAMESPACE_HTML,
  INFRA_NAMESPACE_MATHML,
  INFRA_NAMESPACE_SVG,
  INFRA_NAMESPACE_XLINK,
  INFRA_NAMESPACE_XML,
  INFRA_NAMESPACE_XMLNS,

  NUM_INFRA_NAMESPACE,
};

#endif /* _LIBWFS_INFRA_NAMESPACE_H */
